photos_index:
    path:     /
    defaults: { _controller: "ArtimonePartheBundle:Photos:index" }
    methods:  GET

photos_show:
    path:     /{id}/show
    defaults: { _controller: "ArtimonePartheBundle:Photos:show" }
    methods:  GET

photos_new:
    path:     /new
    defaults: { _controller: "ArtimonePartheBundle:Photos:new" }
    methods:  [GET, POST]

photos_edit:
    path:     /{id}/edit
    defaults: { _controller: "ArtimonePartheBundle:Photos:edit" }
    methods:  [GET, POST]

photos_delete:
    path:     /{id}/delete
    defaults: { _controller: "ArtimonePartheBundle:Photos:delete" }
    methods:  DELETE
