<?php

namespace Artimone\BlogBundle\Repository;

/**
 * AnnonceSkillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceSkillRepository extends \Doctrine\ORM\EntityRepository
{
}
