artimone_blog_annonce:
    resource: "@ArtimoneBlogBundle/Resources/config/routing/annonce.yml"
    prefix:   /annonce
    
artimone_blog_annonceskill:
    resource: "@ArtimoneBlogBundle/Resources/config/routing/annonceskill.yml"
    prefix:   /annonceskill
    
artimone_blog_candidature:
    resource: "@ArtimoneBlogBundle/Resources/config/routing/candidature.yml"
    prefix:   /candidature
    
artimone_blog_gender:
    resource: "@ArtimoneBlogBundle/Resources/config/routing/gender.yml"
    prefix:   /gender

artimone_blog_skill:
    resource: "@ArtimoneBlogBundle/Resources/config/routing/skill.yml"
    prefix:   /skill

