artimone_blog_homepage:
    path:     /{page}
    defaults: { _controller: ArtimoneBlogBundle:Annonce:index, page: 1 }
    requirements:
        page: \d+
    
artimone_blog_show:
    path: /show/{id}
    defaults: { _controller: ArtimoneBlogBundle:Annonce:show }    
    requirements:
        id: \d+
        
artimone_blog_new:
    path: /new
    defaults: { _controller: ArtimoneBlogBundle:Annonce:new }   
    
artimone_blog_edit:
    path: /edit/{id}
    defaults: { _controller: ArtimoneBlogBundle:Annonce:edit }
    requirements:
        id: \d+    
artimone_blog_delete:
    path: /delete/{id}
    defaults: { _controller: ArtimoneBlogBundle:Annonce:delete }
    requirements:
        id: \d+
