gender_index:
    path:     /
    defaults: { _controller: "ArtimoneBlogBundle:Gender:index" }
    methods:  GET

gender_show:
    path:     /{id}/show
    defaults: { _controller: "ArtimoneBlogBundle:Gender:show" }
    methods:  GET

gender_new:
    path:     /new
    defaults: { _controller: "ArtimoneBlogBundle:Gender:new" }
    methods:  [GET, POST]

gender_edit:
    path:     /{id}/edit
    defaults: { _controller: "ArtimoneBlogBundle:Gender:edit" }
    methods:  [GET, POST]

gender_delete:
    path:     /{id}/delete
    defaults: { _controller: "ArtimoneBlogBundle:Gender:delete" }
    methods:  DELETE
